import * as React from 'react';
import { useState } from 'react';
// import { Row, Col, Card, Form, Button } from 'react-bootstrap';
import Select from 'react-select';
import { ValidationForm, TextInput, BaseFormControl, SelectGroup, FileInput, Checkbox, Radio } from 'react-bootstrap4-form-validation';
import { Row, Col, Card, Button } from 'react-bootstrap';
import { Formik, Field, Form, ErrorMessage } from 'formik';
import * as Yup from 'yup';
import Datetime from 'react-datetime';
import MaskedInput from 'react-text-mask';
import validator from 'validator';
import AnimatedModal from '../../App/components/AnimatedModal';